<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository {

    public function getChildren($id) {
        $qb = $this->createQuery("SELECT id, name, tags, parent, language FROM categories
WHERE parent = :id")->setParameter('id', $id);

        return $qb->getQuery()->getResult();
    }
    
    public function getCatAndChildren($id) {
        $qb = $this->createQuery("SELECT id, name, tags, parent, language FROM categories
WHERE id = :id
OR parent = :id")->setParameter('id', $id);

        return $qb->getQuery()->getResult();
    }

}