<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository {

    public function getCategoryAndSurroundings($id) {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.id = :id')
                ->orWhere('c.parent = :id')
                ->orWhere('c.id = (SELECT parent FROM categories WHERE id = :id)')
                ->setParameter('id', $id);

        return $qb->getQuery()->getResult();
    }

}